python 可以讓我們去捕捉異常跟撰寫異常處理程序。

```python
# 除數為0
def division(x, y):
    return x / y

print(division(10, 2))
print(division(6, 3))
print(division(5, 0))

# 5.0
# 2.0

# ---------------------------------------------------------------------------
# ZeroDivisionError                         Traceback (most recent call last)
# Cell In[2], line 7
#       5 print(division(10, 2))
#       6 print(division(6, 3))
# ----> 7 print(division(5, 0))

# Cell In[2], line 3
#       2 def division(x, y):
# ----> 3     return x / y

# ZeroDivisionError: division by zero
```

## 1. ZeroDivisionError

所以，我們可以使用`try except來捕捉異常`

```python
def division(x, y):
    try:                        # try - except指令
        return x / y
    except ZeroDivisionError:   # 除數為0時執行
        print("除數不可為0")

print(division(10, 2))          # 5.0
print(division(5, 0))           # 除數不可為0
print(division(6, 3))           # 2.0

# 5.0
# 除數不可為0
# None
# 2.0
```

所以，我們來看看異常處理的整個架構：

-   try -> 預想可能會發生錯誤的指令
-   except -> 抓錯
-   else -> 沒事，繼續跑

```python
def division(x, y):
    try:                        # try - except指令
        ans =  x / y
        # return ans
    except ZeroDivisionError:   # 除數為0時執行
        print("除數不可為0")
    else:
        return ans              # 傳回正確的執行結果

print(division(10, 2))
print(division(5, 0))
print(division(6, 3))

# 5.0
# 除數不可為0
# None
# 2.0
```

## 2. 找不到檔案 file not found error

```python
fn = 'data.txt'
try:
    with open(fn) as file_Obj:
        data = file_Obj.read()
except FileNotFoundError:
    print(f"找不到 {fn} 檔案")
else:
    print(data)
```

## 3. 常見異常處裡

![upgit_20240816_1723810259.png](https://raw.githubusercontent.com/kcwc1029/obsidian-upgit-image/main/2024/08/upgit_20240816_1723810259.png)

## 4. 設計多組異常處理程序

```python
def division(x, y):
    try:
        return x / y
    except (ZeroDivisionError, TypeError) as e:   # 2個異常
        print(e)

print(division(10, 2))
print(division(5, 0))     # division by zero
print(division('a', 'b'))  # unsupported operand type(s) for /: 'str' and 'str'
print(division(6, 3))
```

> 通用錯誤

```python
def division(x, y):
    try:
        return x / y
    except :
        return "有錯誤"

print(division(10, 2))
print(division(5, 0))
print(division('a', 'b'))
print(division(6, 3))

# 5.0
# 有錯誤
# 有錯誤
# 2.0
```

```python
# 通用錯誤
def division(x, y):
    try:
        return x / y
    except Exception as e:
        return e

print(division(10, 2))
print(division(5, 0))           #
print(division('a', 'b'))
print(division(6, 3))
# 5.0
# division by zero
# unsupported operand type(s) for /: 'str' and 'str'
# 2.0
```

## 5. finally

他是【是否有錯】，都一定會執行

```python
def division(x, y):
    try:
        print(x / y)
        # return  x / y  # 如果這邊下return，就直接結束，就沒有後面了
    except Exception as e:
        print(e)
    finally:                         # 離開函數前先執行此程式碼
        print("complete")


division(10, 2)
division(5, 0)
division('a', 'b')
division(6, 3)
```

## 6. 丟出異常 raise

-   前面的部分，著重於 python 發現異常後，丟出異常，如果不處理就中止執行
-   如果要改為，發現異常後會丟出異常，並且跳到設計好的 except 去處理

```python
def passWord(pwd):
    """檢查密碼長度必須是5到8個字元"""
    pwdlen = len(pwd)                       # 密碼長度
    if pwdlen < 5:                          # 密碼長度不足
        raise Exception('password too short')
    if pwdlen > 8:                          # 密碼長度太長
        raise Exception('password too long')
    print('correct')

for pwd in ('aaabbbccc', 'aaa', 'aaabbb'):  # 測試系列密碼值
    try:
        passWord(pwd)
    except Exception as e:
        print(str(e))
# password too long
# password too short
# correct
```

## 7. 紀錄 Traceback 字串

```python
import traceback


def passWord(pwd):
    """檢查密碼長度必須是5到8個字元"""
    pwdlen = len(pwd)                       # 密碼長度
    if pwdlen < 5:                          # 密碼長度不足
        raise Exception('password too short')
    if pwdlen > 8:                          # 密碼長度太長
        raise Exception('password too long')
    return "correct"

for pwd in ('aaabbbccc', 'aaa', 'aaabbb'):  # 測試系列密碼值
    try:
        print(passWord(pwd))

    except Exception as e:
        print(str(e))
        errlog = open('err.txt', 'a')   # 開啟錯誤檔案
        errlog.write(traceback.format_exc())   # 寫入錯誤檔案
        errlog.close()                         # 關閉錯誤檔案
# password too long
# password too short
# correct
```

## 8. 程式斷言 assert

> 基本語法：`assert 條件, "錯誤信息"`

主要用於開發階段做檢查

-   如果條件為 True，程式繼續執行。
-   如果條件為 False，程式會引發 AssertionError，並終止執行。

```python
class Banks():
   # 定義銀行類別
    title = 'Tainan Bank'
    def __init__(self, uname, money):
        self.name = uname
        self.balance = money

    def save_money(self, money):            # 設計存款方法
        self.balance += money
        print("save money", money)

    def withdraw_money(self, money):        # 設計提款方法
        self.balance -= money               # 執行提款
        print("Withdrawal money", money)

    def get_balance(self):                  # 獲得存款餘額
        print("Current balance ", self.balance)
```

```python
hungbank = Banks('TA', 100)
hungbank.get_balance()                      # 獲得存款餘額
hungbank.save_money(-300)                   # 存款-300元
hungbank.get_balance()                      # 獲得存款餘額
hungbank.withdraw_money(700)                # 提款700元
hungbank.get_balance()                      # 獲得存款餘額

# 之所以會錯誤是因為，我們在提款前，應該要先檢查帳戶餘額
```

```python
# 增加assert後
class Banks():
   # 定義銀行類別
    title = 'Tainan Bank'
    def __init__(self, uname, money):
        self.name = uname
        self.balance = money

    def save_money(self, money):           # 設計存款方法
        assert money > 0, 'money must > 0'
        self.balance += money
        print("save money", money)

    def withdraw_money(self, money):        # 設計提款方法
        assert money > 0, 'withdraw must > 0'
        assert money <= self.balance, 'money not enough'
        self.balance -= money               # 執行提款
        print("Withdrawal money", money)

    def get_balance(self):                  # 獲得存款餘額
        print("Current balance ", self.balance)
```

```python
hungbank = Banks('TA', 100)
hungbank.get_balance()                      # 獲得存款餘額
hungbank.save_money(300)                   # 存款300元
# hungbank.get_balance()                      # 獲得存款餘額
# hungbank.withdraw_money(700)                # 提款700元
# hungbank.get_balance()                      # 獲得存款餘額

# 之所以會錯誤是因為，我們在提款前，應該要先檢查帳戶餘額
```

## 9. 程式日誌模組 logging

-   logging 模組是 Python 的內建功能，用來追蹤程式的運行過程。它提供了不同等級的日誌紀錄，從詳細的調試資訊到嚴重錯誤訊息，都可以根據需求進行設定與輸出。

### 9.1. logging level(低到高)

-   DEBUG ：
    -   用於顯示程式的小細節，是最低層級的內容。
    -   通常在調試程式問題時使用，可追蹤關鍵變數的變化過程。
-   INFO ：

    -   用於記錄程式一般發生的事件。

-   WARNING ：
    -   用於顯示可能影響程式執行但尚未造成問題的事件，未來可能導致問題的發生。
-   ERROR ：
    -   顯示程式發生的錯誤，通常是在某些狀態下引發錯誤的原因。
-   CRITICAL ：
    -   通常表示將導致系統崩潰或中斷的錯誤。

```python
import logging

# 設定 logging 等級為 DEBUG，這樣所有等級的訊息都會顯示
logging.basicConfig(level=logging.WARNING)

logging.debug('This is a DEBUG message')    # 顯示調試資訊
logging.info('This is an INFO message')     # 顯示一般資訊
logging.warning('This is a WARNING message') # 顯示警告資訊
logging.error('This is an ERROR message')   # 顯示錯誤資訊
logging.critical('This is a CRITICAL message') # 顯示嚴重錯誤資訊
```

```python
import logging

# 設定 logging 等級為 WARNING，DEBUG 和 INFO 等級將不顯示
logging.basicConfig(level=logging.WARNING)

logging.debug('This will not show')         # 不會顯示
logging.info('This will not show either')   # 不會顯示
logging.warning('This is a WARNING message') # 顯示警告資訊
logging.error('This is an ERROR message')   # 顯示錯誤資訊
logging.critical('This is a CRITICAL message') # 顯示嚴重錯誤資訊
```

![upgit_20241021_1729490900.png](https://raw.githubusercontent.com/kcwc1029/obsidian-upgit-image/main/2024/10/upgit_20241021_1729490900.png)
